spring.application.name=WhatsApp
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/whatsapp
spring.datasource.username=whatsapp
spring.datasource.password=BCA21DC612280ABFBA68CE8500EC945C92EF9F1CABC4AD7F48343F62FEB87F6A
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1200000
spring.jpa.properties.hibernate.search.backend.analysis.configurer=whatsapp.configuration.LuceneAnalysisConfig
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.access.name=accessToken
jwt.access.secret=BCA21DC612280ABFBA68CE8500EC945C92EF9F1CABC4AD7F48343F62FEB87F6A
jwt.access.expiration=900000
jwt.refresh.name=refreshToken
jwt.refresh.secret=8AD65E4438EE03C87BC40F72C1AD43833B3C7B50992A54F15689FB1A5DF2DD34
jwt.refresh.expiration=86400000
app.cookie.secure=true
app.cookie.same-site=Lax
app.cors.allowed-origins=http://localhost:3000,http://localhost:5173,http://localhost:8080,https://reliant-mumble-unmindful.ngrok-free.dev/
file.upload-dir=D:/WhatsApp/Uploads/User_Files
profile.pic.upload-dir=D:/WhatsApp/Uploads/Profile_Pics
default.profile.pic.name=default.png
spring.servlet.multipart.max-file-size=1024MB
spring.servlet.multipart.max-request-size=1024MB
file.blocked-extensions=
profile.pic.allowed-types=image/jpeg,image/jpg,image/png,image/webp,image/gif
profile.pic.allowed-size=10
file.cache.max-age=24h
profile.pic.cache.max-age=0s
hibernate.search.reindex-on-startup=false
spring.data.web.pageable.default-page-size=20
spring.data.web.pageable.max-page-size=30
spring.data.web.pageable.page-parameter=page